---- CREACION DE SECUENCIAS
---TABLA HOSPITALARIO.SNH_MST_HISTORIA_CLINICA

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_HISTORIA_CLINICA_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;

ALTER TABLE HOSPITALARIO.SNH_MST_HISTORIA_CLINICA MODIFY HISTORIA_CLINICA_ID  DEFAULT SEQ_SNH_HISTORIA_CLINICA_ID.nextval;

---TABLA HOSPITALARIO.SNH_DET_HISTORIA_CLINICA

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_DET_HISTORIA_CLINICA_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;

ALTER TABLE HOSPITALARIO.SNH_DET_HISTORIA_CLINICA MODIFY DET_HISTORIA_CLINICA_ID  DEFAULT SEQ_DET_HISTORIA_CLINICA_ID.nextval;




--- Secuencia para la tabla SNH_MST_ANTE_PARTO

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_ANTE_PARTO_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PARTO MODIFY ANTE_PARTO_ID  DEFAULT SEQ_SNH_ANTE_PARTO_ID.nextval;

----Secuencia para la tabla SNH_MST_ANTE_POSTNATALES

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_ANTE_POSTNATALES_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_POSTNATALES MODIFY ANTE_POSTNATALES_ID   DEFAULT SEQ_SNH_ANTE_POSTNATALES_ID.nextval;

---- Secuencia para la tabla  	

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_ALIMEN_PEDIATRICA_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;

ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA MODIFY ALIMEN_PEDIATRICA_ID   DEFAULT SEQ_SNH_ALIMEN_PEDIATRICA_ID.nextval;


---- Secuencia para la tabla SNH_MST_ANTE_PSICOMOTOR 	

CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_ANTE_PSICOMOTOR_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PSICOMOTOR MODIFY ANTE_PSICOMOTOR_ID   DEFAULT SEQ_SNH_ANTE_PSICOMOTOR_ID.nextval;


---- Secuencia para la tabla 


CREATE SEQUENCE  "HOSPITALARIO"."SEQ_SNH_ANTE_SOCECONOMICO_ID" 
MINVALUE 1 MAXVALUE 999999999999999999
INCREMENT BY 1 START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE  
NOKEEP 
NOSCALE  
GLOBAL ;

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO MODIFY ANTE_SOCIOECONOMICO_ID   DEFAULT SEQ_SNH_ANTE_SOCECONOMICO_ID.nextval;

