/*
Created: 07/07/2022
Modified: 29/07/2022
Model: RE Oracle 19c
Database: Oracle 19c
*/


-- Create tables section -------------------------------------------------

-- Table HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO

CREATE TABLE "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"(
  "ANTE_SOCIOECONOMICO_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0),
  "CASA" Number(10,0),
  "PAREDES" Number(10,0),
  "PISO" Number(10,0),
  "TECHO" Number(10,0),
  "SERVICIOS_HIGIENICOS" Varchar2(50 ),
  "HABITACIONES" Number(10,0),
  "AGUA" Number(10,0),
  "LUGAR_AGUA" Number(10,0),
  "LUZ" Number(10,0),
  "LUGAR_EXCRETAS" Number(10,0),
  "NUMERO_PERSONAS" Number(10,0),
  "ANIMALES" Number(10,0),
  "TELEFONO" Number(10,0),
  "OBSERVACIONES" Varchar2(250 ),
  "OTROS" Varchar2(1000 ),
  "HACIMIENTO" Number,
  "ESTADO_REGISTRO" Number NOT NULL,
  "USUARIO_REGISTRO" Number NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_MODIFICACION" Number,
  "FECHA_MODIFICACION" Date
)
/

-- Add keys for table HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO

ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO" ADD CONSTRAINT "PK_SNH_MST_ANTE_SOCIOECONOMICO" PRIMARY KEY ("ANTE_SOCIOECONOMICO_ID")
/

-- Table and Columns comments section

COMMENT ON TABLE "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO" IS 'Esta Tabla almacena los antecedentes socioeconomicos de la historia clinica pediatrica y los datos de la vivivienda de la historia clínica de adolescente'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."ANTE_SOCIOECONOMICO_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."HISTORIA_CLINICA_ID" IS 'Llave Foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."CASA" IS 'Catalogo Prestablecido Tipo de casa en la que habita'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."PAREDES" IS 'Catalogo Prestablecido tipo de paredes de la casa en la que habita'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."PISO" IS 'Catalogo Prestablecido tipo de piso de la vivienda en la que habita. ejemplo ladrillo, tierra, embaldosado etc'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."TECHO" IS 'Catalogo Prestablecido tipo de techo de la vivienda en la que habita, ejmplo zinc teja, paja etc.'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."SERVICIOS_HIGIENICOS" IS 'Descripción Servicios higiénicos'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."HABITACIONES" IS 'Numero de habitaciones de la vivienda en la que habita'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."AGUA" IS 'Catalogo prestablecido con posible valor si/no que indica si tiene servicio de agua en la vivienda'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."LUGAR_AGUA" IS 'Catalogo Prestablecido para indicar si el agua la tiene en casa o fuera de casa'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."LUZ" IS 'Catalogo prestablecido con posible valor si/ no que indica si tiene servicio de luz. Aplica para la historia de adolescentes y pediatrica'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."LUGAR_EXCRETAS" IS 'Catalogo Prestablecido que indica que lugar excreta si en el hogar o fuera del hogar'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."NUMERO_PERSONAS" IS 'Numero de personas con la que convive'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."ANIMALES" IS 'Catalogo Prestablecido que indica si en el hogar hay animales si/no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."TELEFONO" IS 'Numero de Teléfono de la vivienda'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."OBSERVACIONES" IS 'Observaciones de los antecedentes socioeconómicos, aplica tanto para la historia clinica de adolescente como la pediátrica'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."OTROS" IS 'Otro Indicador socioeconómico '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."HACIMIENTO" IS 'Catalogo prestablecido para indicar si está en hacimiento si/no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."ESTADO_REGISTRO" IS 'Catalogo Prestablecido estado del registro de antecedentes socioeconómicos'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."USUARIO_REGISTRO" IS 'Usuario que agregó los antecedentes socioeconómicos'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."FECHA_REGISTRO" IS 'Fecha en que se agregaron los antecedentes socioeconómicos'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."USUARIO_MODIFICACION" IS 'Último usuario que modificó los antecendentes socioeconómicos'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO"."FECHA_MODIFICACION" IS 'Última Fecha en la que se modificó los antecedentes socioeconómicos'
/

-- Table HOSPITALARIO.SNH_MST_FAMILIA

CREATE TABLE "HOSPITALARIO"."SNH_MST_FAMILIA"(
  "ANT_FAMILIAR_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0),
  "VIVE" Number(10,0),
  "PERCEPCION_FAMILIAR" Number(10,0),
  "OBSERVACIONES" Varchar2(250 ),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "USUARIO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_MODIFICACION" Number(10,0),
  "FECHA_MODIFICACION" Date
)
/

-- Add keys for table HOSPITALARIO.SNH_MST_FAMILIA

ALTER TABLE "HOSPITALARIO"."SNH_MST_FAMILIA" ADD CONSTRAINT "PK_SNH_MST_FAMILIA" PRIMARY KEY ("ANT_FAMILIAR_ID")
/

-- Table and Columns comments section

COMMENT ON TABLE "HOSPITALARIO"."SNH_MST_FAMILIA" IS 'Esta Tabla almacena los antecedentes familiares correspondientes a la historia clínica del adolescente'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."ANT_FAMILIAR_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."HISTORIA_CLINICA_ID" IS 'Llave foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."VIVE" IS 'Catalogo Predefinido que indica la forma en donde vive el paciente, siendo los valores : solo, en casa, en la calle, institución protectora, privado de libertad
'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."PERCEPCION_FAMILIAR" IS 'Catalogo Predefinido que indica la percepción familiar, siendo los valores, bueno, regular, mala, no hay relación '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."OBSERVACIONES" IS 'Observaciones'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."ESTADO_REGISTRO" IS 'Catalogo Predefinido que indica el estado del registro de los antecedentes familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."USUARIO_REGISTRO" IS 'Usuario que agregó los datos de los antecedentes familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."FECHA_REGISTRO" IS 'Fecha en que se registraron los antecedentes familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."USUARIO_MODIFICACION" IS 'Último usuario que modificó los antecedentes familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_FAMILIA"."FECHA_MODIFICACION" IS 'Última fecha en que se modificó los antecedentes familiares'
/

-- Table HOSPITALARIO.SNH_MST_ENFER_FAMILIARES

CREATE TABLE "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"(
  "ENFER_FAMILIARES_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0) NOT NULL,
  "TIPO_ENFERMEDAD" Number(10,0),
  "VALOR_ENFERMEDAD" Number(10,0),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "USUARIO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_MODIFICACION" Number(10,0),
  "FECHA_MODIFICACION" Date
)
/

-- Add keys for table HOSPITALARIO.SNH_MST_ENFER_FAMILIARES

ALTER TABLE "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES" ADD CONSTRAINT "PK_SNH_MST_ENFER_FAMILIARES" PRIMARY KEY ("ENFER_FAMILIARES_ID")
/

-- Table and Columns comments section

COMMENT ON TABLE "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES" IS 'Esta tabla almacena los datos de los antecedentes familiares correspondientes a la seccion Antecedentes familiares de la historia clínica del adolescente y antecedentes familiares patológicos de la historia clínica del adulto'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."ENFER_FAMILIARES_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."HISTORIA_CLINICA_ID" IS 'Llave Foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."TIPO_ENFERMEDAD" IS 'Catalogo Predefinido del tipo de enfermedad '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."VALOR_ENFERMEDAD" IS 'Catalogo Predefinido de las enfermedades de acuerdo al tipo de enfermedad'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."ESTADO_REGISTRO" IS 'Catalogo Predefinido del estado del registro de los antecedentes de las enfermedades familiares '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."USUARIO_REGISTRO" IS 'Usuario que registró los datos de  los antecedentes de las enfermedades familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."FECHA_REGISTRO" IS 'Fecha en la  que se registró los datos de  los antecedentes de las enfermedades familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."USUARIO_MODIFICACION" IS 'Último usuario que modificó   los datos de  los antecedentes de las enfermedades familiares'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES"."FECHA_MODIFICACION" IS 'Última fecha en la que se modificaron  los datos de  los antecedentes de las enfermedades familiares'
/

-- Table HOSPITALARIO.SNH_MST_VIDA_SOCIAL

CREATE TABLE "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"(
  "VIDA_SOCIAL_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0),
  "ACEPTACION" Number(10,0),
  "PAREJA" Number(10,0),
  "EDAD_PAREJA_ANNIOS" Number(10,0),
  "EDAD_PAREJA_MESES" Number(10,0),
  "VIOLENCIA_PAREJA" Number(10,0),
  "AMIGOS" Number(10,0),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "USUARIO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_MODIFICACION" Number(10,0),
  "FECHA_MODIFICACION" Date
)
/

-- Add keys for table HOSPITALARIO.SNH_MST_VIDA_SOCIAL

ALTER TABLE "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL" ADD CONSTRAINT "PK_SNH_MST_VIDA_SOCIAL" PRIMARY KEY ("VIDA_SOCIAL_ID")
/

-- Table and Columns comments section

COMMENT ON TABLE "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL" IS 'Esta tabla almacena los datos de la vida social correspondiente a la historia clinica del adolescente'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."VIDA_SOCIAL_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."HISTORIA_CLINICA_ID" IS 'Llave foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."ACEPTACION" IS 'Catalogo Predefinido que indica el nivel de aceptación.'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."PAREJA" IS 'Catalogo Predefinido que indica si tiene pareja, siendo los valores si/no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."EDAD_PAREJA_ANNIOS" IS 'Edad en años con la pareja'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."EDAD_PAREJA_MESES" IS 'Edad en meses con la pareja'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."VIOLENCIA_PAREJA" IS 'Catalogo Predefinido que indica si recibe violencia de la pareja, siendo los valores si / no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."AMIGOS" IS 'Catalogo Predefinido que indica si tiene amigos, siendo los valores si/no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."ESTADO_REGISTRO" IS 'Catalogo Predefinido que indica el estado del registro '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."USUARIO_REGISTRO" IS 'Usuario que registró los datos de vida social'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."FECHA_REGISTRO" IS 'Fecha en la que se registró los datos de la vida social'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."USUARIO_MODIFICACION" IS 'Último Usuario que modificó el registro de vida social'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL"."FECHA_MODIFICACION" IS 'Última Fecha de Modificación del registro de vidad social'
/

-- Table HOSPITALARIO.SNH_MST_PSICOEMOCIONAL

CREATE TABLE "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"(
  "PSICOEMOCIONAL_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0),
  "IMAGEN_CORPORAL" Number(10,0),
  "ESTADO_ANIMO" Number(10,0),
  "REFERENTE_ADULTO" Number(10,0),
  "PROYECTO_VIDA" Number(10,0),
  "APOYO_REDES" Number(10,0),
  "TELEFONO_ADULTO" Number(10,0),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "USUARIO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_MODIFICACION" Number(10,0),
  "FECHA_MODIFICACION" Date
)
/

-- Add keys for table HOSPITALARIO.SNH_MST_PSICOEMOCIONAL

ALTER TABLE "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL" ADD CONSTRAINT "PK_SNH_MST_PSICOEMOCIONAL" PRIMARY KEY ("PSICOEMOCIONAL_ID")
/

-- Table and Columns comments section

COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."PSICOEMOCIONAL_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."HISTORIA_CLINICA_ID" IS 'Llave foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."IMAGEN_CORPORAL" IS 'Catalogo Predefinido que indica la imagen corporal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."ESTADO_ANIMO" IS 'Catalogo Predefinido que indica el estado de ánimo'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."REFERENTE_ADULTO" IS 'Catalogo Predefinido que indica la referencia del adulto'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."PROYECTO_VIDA" IS 'Catalogo Predefinido que indica si tiene un proyecto de vida'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."APOYO_REDES" IS 'Catalogo predefinido que indica si tiene apoyo en redes, siendo los valores si/no'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."TELEFONO_ADULTO" IS 'Numero de Telefono del adulto'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."ESTADO_REGISTRO" IS 'Catalogo Predefinido que indica el estado del registro del antecedentes psicoemocional'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."USUARIO_REGISTRO" IS 'Usuario que registró el antecedente psicoemocional'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."FECHA_REGISTRO" IS 'Fecha en la que se registraron los antecedentes psicoemocionales'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."USUARIO_MODIFICACION" IS 'Último Usuario que modificó los antecedentes psicoemocionales'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL"."FECHA_MODIFICACION" IS 'Última Fecha de modificación de los antecedentes psicoemocionales'
/



-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "SNH_DET_ANTE_ENFERMEDADES" ADD CONSTRAINT "FRK_MST_ANTE_ENFER_DETENFERM" FOREIGN KEY ("ANTE_ENFERMEDADES_ID") REFERENCES "HOSPITALARIO"."SNH_MST_ANTE_ENFERMEDADES" ("ANTE_ENFERMEDADES_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_HIST_LABORAL" ADD CONSTRAINT "FRK_REL_HIST_LABORAL_DETHLAB" FOREIGN KEY ("HIST_LABORAL_ID") REFERENCES "HOSPITALARIO"."SNH_REL_HIST_LABORAL" ("HIST_LABORAL_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_POSTNATALES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_POST" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_PARTO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PAR" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_REL_HIST_LABORAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_HLAB" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_ENFERMEDADES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_ENF" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_PSICOMOTOR" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PSIC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ALIMEN_PEDIATRICA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_ALIM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SOCE" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_HISTORIA_CLINICA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_DETHC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_HIST_SERVICIOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SER" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANT_PERSONALES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_APER" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_FAMILIA" ADD CONSTRAINT "FRK_FAMILIAID_DET_FAMILIA" FOREIGN KEY ("ANT_FAMILIAR_ID") REFERENCES "HOSPITALARIO"."SNH_MST_FAMILIA" ("ANT_FAMILIAR_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_FAMILIA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_FAM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EDUCACION" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EDU" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EFAM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EXAMEN_FISICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EF" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EXAMEN_ADOLES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EXAD" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_FAMILIA_CONVIVE" ADD CONSTRAINT "FRK_FAMILIAID_FAMILIACONVIVE" FOREIGN KEY ("ANT_FAMILIAR_ID") REFERENCES "HOSPITALARIO"."SNH_MST_FAMILIA" ("ANT_FAMILIAR_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANT_GINECOOBSTETRICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_GINE" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANT_UROLOGICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_URO" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_SEXUALIDAD" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SEX" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_HABITOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_HAB" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_CONSUMOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_CONS" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_VISOC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PSEM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_VACUNAS" ADD CONSTRAINT "FK_MST_HISTORIA_CLINICA_VACUN" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



-- Grant permissions section -------------------------------------------------

GRANT "CONNECT" TO "GSMROOTUSER_ROLE"
/
GRANT "CONNECT" TO "GSMADMIN_ROLE"
/
GRANT "CONNECT" TO "GSM_POOLADMIN_ROLE"
/
GRANT "CONNECT" TO "DV_ACCTMGR"
/
GRANT "CONNECT" TO "SYS"
/
GRANT "RESOURCE" TO "LOGSTDBY_ADMINISTRATOR"
/
GRANT "RESOURCE" TO "SYS"
/
GRANT "RESOURCE" TO "XDB"
/
GRANT "DBA" TO "SYSTEM"
/
GRANT "DBA" TO "SYS"
/
GRANT "PDB_DBA" TO "SYS"
/
GRANT "AUDIT_ADMIN" TO "SYS"
/
GRANT "AUDIT_VIEWER" TO "SYS"
/
GRANT "SELECT_CATALOG_ROLE" TO "DBA"
/
GRANT "SELECT_CATALOG_ROLE" TO "EXP_FULL_DATABASE"
/
GRANT "SELECT_CATALOG_ROLE" TO "IMP_FULL_DATABASE"
/
GRANT "SELECT_CATALOG_ROLE" TO "EM_EXPRESS_BASIC"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYSUMF_ROLE"
/
GRANT "SELECT_CATALOG_ROLE" TO "OEM_MONITOR"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYS"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYSBACKUP"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "DBA"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "EXP_FULL_DATABASE"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "IMP_FULL_DATABASE"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "SYS"
/
GRANT "CAPTURE_ADMIN" TO "DBA"
/
GRANT "CAPTURE_ADMIN" TO "SYS"
/
GRANT "EXP_FULL_DATABASE" TO "DBA"
/
GRANT "EXP_FULL_DATABASE" TO "DATAPUMP_EXP_FULL_DATABASE"
/
GRANT "EXP_FULL_DATABASE" TO "DATAPUMP_IMP_FULL_DATABASE"
/
GRANT "EXP_FULL_DATABASE" TO "SYS"
/
GRANT "IMP_FULL_DATABASE" TO "DBA"
/
GRANT "IMP_FULL_DATABASE" TO "DATAPUMP_IMP_FULL_DATABASE"
/
GRANT "IMP_FULL_DATABASE" TO "SYS"
/
GRANT "AVTUNE_PKG_ROLE" TO "SYS"
/
GRANT "XS_CONNECT" TO "SYS"
/
GRANT "CDB_DBA" TO "DBSNMP"
/
GRANT "CDB_DBA" TO "SYS"
/
GRANT "APPLICATION_TRACE_VIEWER" TO "SYS"
/
GRANT "ACCHK_READ" TO "DBA"
/
GRANT "ACCHK_READ" TO "SYS"
/
GRANT "LOGSTDBY_ADMINISTRATOR" TO "SYS"
/
GRANT "DBFS_ROLE" TO "SYS"
/
GRANT "DBFS_ROLE" TO "XDB"
/
GRANT "GSMUSER_ROLE" TO "SYS"
/
GRANT "GSMUSER_ROLE" TO "GSMUSER"
/
GRANT "GSMROOTUSER_ROLE" TO "SYS"
/
GRANT "GSMROOTUSER_ROLE" TO "GSMROOTUSER"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "DBA"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "GSMUSER_ROLE"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "SYS"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "GSMADMIN_INTERNAL"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "DBA"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "SYS"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "GSMADMIN_INTERNAL"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "GSMADMIN_ROLE"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYSTEM"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "GSMCATUSER"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYS"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYSRAC"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "MDSYS"
/
GRANT "AQ_USER_ROLE" TO "SYS"
/
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "SYS"
/
GRANT "PROVISIONER" TO "SYS"
/
GRANT "XS_SESSION_ADMIN" TO "SYS"
/
GRANT "XS_NAMESPACE_ADMIN" TO "SYS"
/
GRANT "XS_CACHE_ADMIN" TO "SYS"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "SELECT_CATALOG_ROLE"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "HS_ADMIN_ROLE"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "SYS"
/
GRANT "GATHER_SYSTEM_STATISTICS" TO "DBA"
/
GRANT "GATHER_SYSTEM_STATISTICS" TO "SYS"
/
GRANT "OPTIMIZER_PROCESSING_RATE" TO "DBA"
/
GRANT "OPTIMIZER_PROCESSING_RATE" TO "SYS"
/
GRANT "DBMS_MDX_INTERNAL" TO "SYS"
/
GRANT "BDSQL_ADMIN" TO "SYS"
/
GRANT "BDSQL_USER" TO "SYS"
/
GRANT "RECOVERY_CATALOG_OWNER" TO "RECOVERY_CATALOG_OWNER_VPD"
/
GRANT "RECOVERY_CATALOG_OWNER" TO "SYS"
/
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "SYS"
/
GRANT "RECOVERY_CATALOG_USER" TO "RECOVERY_CATALOG_OWNER_VPD"
/
GRANT "RECOVERY_CATALOG_USER" TO "SYS"
/
GRANT "EM_EXPRESS_BASIC" TO "EM_EXPRESS_ALL"
/
GRANT "EM_EXPRESS_BASIC" TO "SYS"
/
GRANT "EM_EXPRESS_ALL" TO "DBA"
/
GRANT "EM_EXPRESS_ALL" TO "SYS"
/
GRANT "SYSUMF_ROLE" TO "SYS"
/
GRANT "SYSUMF_ROLE" TO "SYS$UMF"
/
GRANT "MAINTPLAN_APP" TO "SYS"
/
GRANT "SCHEDULER_ADMIN" TO "DBA"
/
GRANT "SCHEDULER_ADMIN" TO "SYS"
/
GRANT "PPLB_ROLE" TO "DBA"
/
GRANT "PPLB_ROLE" TO "SYS"
/
GRANT "PPLB_ROLE" TO "DGPDB_INT"
/
GRANT "GDS_CATALOG_SELECT" TO "GSMUSER_ROLE"
/
GRANT "GDS_CATALOG_SELECT" TO "SYS"
/
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "SYS"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "EXECUTE_CATALOG_ROLE"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "HS_ADMIN_ROLE"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "SYS"
/
GRANT "HS_ADMIN_ROLE" TO "SYS"
/
GRANT "OEM_ADVISOR" TO "SYS"
/
GRANT "OEM_MONITOR" TO "DBSNMP"
/
GRANT "OEM_MONITOR" TO "SYS"
/
GRANT "GSMADMIN_ROLE" TO "GSMCATUSER"
/
GRANT "GSMADMIN_ROLE" TO "SYS"
/
GRANT "GSM_POOLADMIN_ROLE" TO "GSMCATUSER"
/
GRANT "GSM_POOLADMIN_ROLE" TO "SYS"
/
GRANT "GSM_POOLADMIN_ROLE" TO "GSMADMIN_INTERNAL"
/
GRANT "GGSYS_ROLE" TO "SYS"
/
GRANT "XDBADMIN" TO "DBA"
/
GRANT "XDBADMIN" TO "GSMADMIN_ROLE"
/
GRANT "XDBADMIN" TO "SYS"
/
GRANT "XDB_SET_INVOKER" TO "DBA"
/
GRANT "XDB_SET_INVOKER" TO "SYS"
/
GRANT "AUTHENTICATEDUSER" TO "SYS"
/
GRANT "XDB_WEBSERVICES" TO "SYS"
/
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "SYS"
/
GRANT "OLAP_XS_ADMIN" TO "DBA"
/
GRANT "OLAP_XS_ADMIN" TO "SYS"
/
GRANT "SODA_APP" TO "RESOURCE"
/
GRANT "SODA_APP" TO "SYS"
/
GRANT "SODA_APP" TO "XDB"
/
GRANT "DATAPATCH_ROLE" TO "SYS"
/
GRANT "WM_ADMIN_ROLE" TO "DBA"
/
GRANT "WM_ADMIN_ROLE" TO "WMSYS"
/
GRANT "JAVAUSERPRIV" TO "JAVASYSPRIV"
/
GRANT "JAVAUSERPRIV" TO "SYS"
/
GRANT "JAVAIDPRIV" TO "SYS"
/
GRANT "JAVASYSPRIV" TO "SYS"
/
GRANT "JAVADEBUGPRIV" TO "SYS"
/
GRANT "EJBCLIENT" TO "SYS"
/
GRANT "JMXSERVER" TO "SYS"
/
GRANT "DBJAVASCRIPT" TO "SYS"
/
GRANT "JAVA_ADMIN" TO "DBA"
/
GRANT "JAVA_ADMIN" TO "SYS"
/
GRANT "CTXAPP" TO "SYS"
/
GRANT "CTXAPP" TO "MDSYS"
/
GRANT "CTXAPP" TO "XDB"
/
GRANT "ORDADMIN" TO "SYS"
/
GRANT "DV_SECANALYST" TO "DV_ADMIN"
/
GRANT "DV_SECANALYST" TO "DV_OWNER"
/
GRANT "OLAP_DBA" TO "DBA"
/
GRANT "OLAP_DBA" TO "SYS"
/
GRANT "OLAP_USER" TO "SYS"
/
GRANT "RDFCTX_ADMIN" TO "SYS"
/
GRANT "LBAC_DBA" TO "SYS"
/
GRANT "LBAC_DBA" TO "LBACSYS"
/
GRANT "DV_MONITOR" TO "DV_OWNER"
/
GRANT "DV_MONITOR" TO "DBSNMP"
/
GRANT "DV_ADMIN" TO "DV_OWNER"
/
GRANT "DV_PATCH_ADMIN" TO "DV_OWNER"
/
GRANT "DV_STREAMS_ADMIN" TO "DV_OWNER"
/
GRANT "DV_GOLDENGATE_ADMIN" TO "DV_OWNER"
/
GRANT "DV_XSTREAM_ADMIN" TO "DV_OWNER"
/
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "DV_OWNER"
/
GRANT "DV_AUDIT_CLEANUP" TO "DV_OWNER"
/
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "DV_OWNER"
/
GRANT "DV_POLICY_OWNER" TO "DV_OWNER"
/

