/*
Created: 7/7/2022
Modified: 11/8/2022
Model: RE Oracle 19c
Database: Oracle 19c
*/


-- Create tables section -------------------------------------------------

-- Table HOSPITALARIO.SNH_CAT_SECCIONES_HISTORIA

CREATE TABLE "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"(
  "SECCIONES_HISTORIA_ID" Number(10,0) NOT NULL,
  "TIPO_HISTORIA" Number(10,0),
  "SECCION_PADRE" Number(10,0),
  "CODIGO" Varchar2(30 ) NOT NULL,
  "VALOR" Varchar2(50 ),
  "DESCRIPCION" Varchar2(100 ),
  "ORDEN" Number(10,0),
  "ES_PASO" Number(10,0),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_REGISTRO" Varchar2(50 ) NOT NULL,
  "FECHA_MODIFICACION" Date,
  "USUARIO_MODIFICACION" Varchar2(50 )
)
/

-- Create indexes for table HOSPITALARIO.SNH_CAT_SECCIONES_HISTORIA

CREATE INDEX "IX_Relationship3" ON "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" ("SECCION_PADRE")
/

-- Add keys for table HOSPITALARIO.SNH_CAT_SECCIONES_HISTORIA

ALTER TABLE "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" ADD CONSTRAINT "PK_SNH_CAT_SECCIONES_HISTORIA" PRIMARY KEY ("SECCIONES_HISTORIA_ID")
/

-- Table and Columns comments section

COMMENT ON TABLE "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" IS 'Esta tabla almacena los valores catalogo de las secciones por cada historia Clinica'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."SECCIONES_HISTORIA_ID" IS 'Llave Principal'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."TIPO_HISTORIA" IS 'Catalogo Predefinido del tipo de historia clinica '
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."SECCION_PADRE" IS 'Id de la sección padre a la que pertenece'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."CODIGO" IS 'Codigo único para identificar la sección'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."VALOR" IS 'Valor Etiqueta de la seccion'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."DESCRIPCION" IS 'Descripcion de la seccion'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."ORDEN" IS 'Ubicación de la Sección en la historia Clinica'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."ES_PASO" IS 'Valor 1 Indica que es un Paso del llenado de la historia Clinica. Valor 0 Corresponde a una Seccion'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."ESTADO_REGISTRO" IS 'Catalogo Predefinido del estado del registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."FECHA_REGISTRO" IS 'Fecha en la que se agregó el dato de la sección'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."USUARIO_REGISTRO" IS 'Usuario que agregó el registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."FECHA_MODIFICACION" IS 'Última Fecha en la que fue modificado el registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA"."USUARIO_MODIFICACION" IS 'Último usuario que modificó el registro'
/

-- Table HOSPITALARIO.SNH_REL_SECCION_HISTORIA

CREATE TABLE "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"(
  "REL_SECCION_HISTORIA_ID" Number(10,0) NOT NULL,
  "HISTORIA_CLINICA_ID" Number(10,0) NOT NULL,
  "SECCIONES_HISTORIA_ID" Number(10,0),
  "ESTADO_REGISTRO" Number(10,0) NOT NULL,
  "FECHA_REGISTRO" Date NOT NULL,
  "USUARIO_REGISTRO" Varchar2(50 ) NOT NULL,
  "FECHA_MODIFICACION" Date,
  "USUARIO_MODIFICACION" Varchar2(50 )
)
/

-- Create indexes for table HOSPITALARIO.SNH_REL_SECCION_HISTORIA

CREATE INDEX "IX_Relationship2" ON "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA" ("SECCIONES_HISTORIA_ID")
/

-- Add keys for table HOSPITALARIO.SNH_REL_SECCION_HISTORIA

ALTER TABLE "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA" ADD CONSTRAINT "PK_SNH_REL_SECCION_HISTORIA" PRIMARY KEY ("REL_SECCION_HISTORIA_ID","HISTORIA_CLINICA_ID")
/

-- Table and Columns comments section

COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."REL_SECCION_HISTORIA_ID" IS 'Llave Primaria'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."HISTORIA_CLINICA_ID" IS 'Llave Foránea de la tabla SNH_MST_HISTORIA_CLINICA'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."ESTADO_REGISTRO" IS 'Catalogo Predefinido del estado del registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."FECHA_REGISTRO" IS 'Fecha en la que se agregó el dato de la sección'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."USUARIO_REGISTRO" IS 'Usuario que agregó el registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."FECHA_MODIFICACION" IS 'Última Fecha en la que fue modificado el registro'
/
COMMENT ON COLUMN "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA"."USUARIO_MODIFICACION" IS 'Último usuario que modificó el registro'
/



-- Create foreign keys (relationships) section ------------------------------------------------- 

ALTER TABLE "SNH_DET_ANTE_ENFERMEDADES" ADD CONSTRAINT "FRK_MST_ANTE_ENFER_DETENFERM" FOREIGN KEY ("ANTE_ENFERMEDADES_ID") REFERENCES "SNH_MST_ANTE_ENFERMEDADES" ("ANTE_ENFERMEDADES_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_HIST_LABORAL" ADD CONSTRAINT "FRK_REL_HIST_LABORAL_DETHLAB" FOREIGN KEY ("HIST_LABORAL_ID") REFERENCES "HOSPITALARIO"."SNH_REL_HIST_LABORAL" ("HIST_LABORAL_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_POSTNATALES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_POST" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_PARTO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PAR" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_REL_HIST_LABORAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_HLAB" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "SNH_MST_ANTE_ENFERMEDADES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_ENF" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_PSICOMOTOR" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PSIC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ALIMEN_PEDIATRICA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_ALIM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANTE_SOCIOECONOMICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SOCE" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_HISTORIA_CLINICA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_DETHC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "SNH_MST_HIST_SERVICIOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SER" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANT_PERSONALES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_APER" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_DET_FAMILIA" ADD CONSTRAINT "FRK_FAMILIAID_DET_FAMILIA" FOREIGN KEY ("ANT_FAMILIAR_ID") REFERENCES "SNH_MST_FAMILIA" ("ANT_FAMILIAR_ID")
/



ALTER TABLE "SNH_MST_FAMILIA" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_FAM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EDUCACION" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EDU" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ENFER_FAMILIARES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EFAM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EXAMEN_FISICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EF" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_EXAMEN_ADOLES" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_EXAD" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_FAMILIA_CONVIVE" ADD CONSTRAINT "FRK_FAMILIAID_FAMILIACONVIVE" FOREIGN KEY ("ANT_FAMILIAR_ID") REFERENCES "SNH_MST_FAMILIA" ("ANT_FAMILIAR_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_ANT_GINECOOBSTETRICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_GINE" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "SNH_MST_ANT_UROLOGICO" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_URO" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "SNH_MST_SEXUALIDAD" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_SEX" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "SNH_MST_HABITOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_HAB" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_CONSUMOS" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_CONS" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_VIDA_SOCIAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_VISOC" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_PSICOEMOCIONAL" ADD CONSTRAINT "FRK_MST_HISTORIA_CLINICA_PSEM" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_MST_VACUNAS" ADD CONSTRAINT "FK_MST_HISTORIA_CLINICA_VACUN" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA" ADD CONSTRAINT "FRK_REL_SECCION_HISTORIA" FOREIGN KEY ("HISTORIA_CLINICA_ID") REFERENCES "HOSPITALARIO"."SNH_MST_HISTORIA_CLINICA" ("HISTORIA_CLINICA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_REL_SECCION_HISTORIA" ADD CONSTRAINT "FRK_SECCION_HISTORIA_ID" FOREIGN KEY ("SECCIONES_HISTORIA_ID") REFERENCES "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" ("SECCIONES_HISTORIA_ID")
/



ALTER TABLE "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" ADD CONSTRAINT "FRK_SECCION_PADRE" FOREIGN KEY ("SECCION_PADRE") REFERENCES "HOSPITALARIO"."SNH_CAT_SECCIONES_HISTORIA" ("SECCIONES_HISTORIA_ID")
/



-- Grant permissions section -------------------------------------------------

GRANT "CONNECT" TO "GSMROOTUSER_ROLE"
/
GRANT "CONNECT" TO "GSMADMIN_ROLE"
/
GRANT "CONNECT" TO "GSM_POOLADMIN_ROLE"
/
GRANT "CONNECT" TO "DV_ACCTMGR"
/
GRANT "CONNECT" TO "SYS"
/
GRANT "RESOURCE" TO "LOGSTDBY_ADMINISTRATOR"
/
GRANT "RESOURCE" TO "SYS"
/
GRANT "RESOURCE" TO "XDB"
/
GRANT "DBA" TO "SYSTEM"
/
GRANT "DBA" TO "SYS"
/
GRANT "PDB_DBA" TO "SYS"
/
GRANT "AUDIT_ADMIN" TO "SYS"
/
GRANT "AUDIT_VIEWER" TO "SYS"
/
GRANT "SELECT_CATALOG_ROLE" TO "DBA"
/
GRANT "SELECT_CATALOG_ROLE" TO "EXP_FULL_DATABASE"
/
GRANT "SELECT_CATALOG_ROLE" TO "IMP_FULL_DATABASE"
/
GRANT "SELECT_CATALOG_ROLE" TO "EM_EXPRESS_BASIC"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYSUMF_ROLE"
/
GRANT "SELECT_CATALOG_ROLE" TO "OEM_MONITOR"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYS"
/
GRANT "SELECT_CATALOG_ROLE" TO "SYSBACKUP"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "DBA"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "EXP_FULL_DATABASE"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "IMP_FULL_DATABASE"
/
GRANT "EXECUTE_CATALOG_ROLE" TO "SYS"
/
GRANT "CAPTURE_ADMIN" TO "DBA"
/
GRANT "CAPTURE_ADMIN" TO "SYS"
/
GRANT "EXP_FULL_DATABASE" TO "DBA"
/
GRANT "EXP_FULL_DATABASE" TO "DATAPUMP_EXP_FULL_DATABASE"
/
GRANT "EXP_FULL_DATABASE" TO "DATAPUMP_IMP_FULL_DATABASE"
/
GRANT "EXP_FULL_DATABASE" TO "SYS"
/
GRANT "IMP_FULL_DATABASE" TO "DBA"
/
GRANT "IMP_FULL_DATABASE" TO "DATAPUMP_IMP_FULL_DATABASE"
/
GRANT "IMP_FULL_DATABASE" TO "SYS"
/
GRANT "AVTUNE_PKG_ROLE" TO "SYS"
/
GRANT "XS_CONNECT" TO "SYS"
/
GRANT "CDB_DBA" TO "DBSNMP"
/
GRANT "CDB_DBA" TO "SYS"
/
GRANT "APPLICATION_TRACE_VIEWER" TO "SYS"
/
GRANT "ACCHK_READ" TO "DBA"
/
GRANT "ACCHK_READ" TO "SYS"
/
GRANT "LOGSTDBY_ADMINISTRATOR" TO "SYS"
/
GRANT "DBFS_ROLE" TO "SYS"
/
GRANT "DBFS_ROLE" TO "XDB"
/
GRANT "GSMUSER_ROLE" TO "SYS"
/
GRANT "GSMUSER_ROLE" TO "GSMUSER"
/
GRANT "GSMROOTUSER_ROLE" TO "SYS"
/
GRANT "GSMROOTUSER_ROLE" TO "GSMROOTUSER"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "DBA"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "GSMUSER_ROLE"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "SYS"
/
GRANT "DATAPUMP_EXP_FULL_DATABASE" TO "GSMADMIN_INTERNAL"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "DBA"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "SYS"
/
GRANT "DATAPUMP_IMP_FULL_DATABASE" TO "GSMADMIN_INTERNAL"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "GSMADMIN_ROLE"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYSTEM"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "GSMCATUSER"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYS"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "SYSRAC"
/
GRANT "AQ_ADMINISTRATOR_ROLE" TO "MDSYS"
/
GRANT "AQ_USER_ROLE" TO "SYS"
/
GRANT "ADM_PARALLEL_EXECUTE_TASK" TO "SYS"
/
GRANT "PROVISIONER" TO "SYS"
/
GRANT "XS_SESSION_ADMIN" TO "SYS"
/
GRANT "XS_NAMESPACE_ADMIN" TO "SYS"
/
GRANT "XS_CACHE_ADMIN" TO "SYS"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "SELECT_CATALOG_ROLE"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "HS_ADMIN_ROLE"
/
GRANT "HS_ADMIN_SELECT_ROLE" TO "SYS"
/
GRANT "GATHER_SYSTEM_STATISTICS" TO "DBA"
/
GRANT "GATHER_SYSTEM_STATISTICS" TO "SYS"
/
GRANT "OPTIMIZER_PROCESSING_RATE" TO "DBA"
/
GRANT "OPTIMIZER_PROCESSING_RATE" TO "SYS"
/
GRANT "DBMS_MDX_INTERNAL" TO "SYS"
/
GRANT "BDSQL_ADMIN" TO "SYS"
/
GRANT "BDSQL_USER" TO "SYS"
/
GRANT "RECOVERY_CATALOG_OWNER" TO "RECOVERY_CATALOG_OWNER_VPD"
/
GRANT "RECOVERY_CATALOG_OWNER" TO "SYS"
/
GRANT "RECOVERY_CATALOG_OWNER_VPD" TO "SYS"
/
GRANT "RECOVERY_CATALOG_USER" TO "RECOVERY_CATALOG_OWNER_VPD"
/
GRANT "RECOVERY_CATALOG_USER" TO "SYS"
/
GRANT "EM_EXPRESS_BASIC" TO "EM_EXPRESS_ALL"
/
GRANT "EM_EXPRESS_BASIC" TO "SYS"
/
GRANT "EM_EXPRESS_ALL" TO "DBA"
/
GRANT "EM_EXPRESS_ALL" TO "SYS"
/
GRANT "SYSUMF_ROLE" TO "SYS"
/
GRANT "SYSUMF_ROLE" TO "SYS$UMF"
/
GRANT "MAINTPLAN_APP" TO "SYS"
/
GRANT "SCHEDULER_ADMIN" TO "DBA"
/
GRANT "SCHEDULER_ADMIN" TO "SYS"
/
GRANT "PPLB_ROLE" TO "DBA"
/
GRANT "PPLB_ROLE" TO "SYS"
/
GRANT "PPLB_ROLE" TO "DGPDB_INT"
/
GRANT "GDS_CATALOG_SELECT" TO "GSMUSER_ROLE"
/
GRANT "GDS_CATALOG_SELECT" TO "SYS"
/
GRANT "XDB_WEBSERVICES_OVER_HTTP" TO "SYS"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "EXECUTE_CATALOG_ROLE"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "HS_ADMIN_ROLE"
/
GRANT "HS_ADMIN_EXECUTE_ROLE" TO "SYS"
/
GRANT "HS_ADMIN_ROLE" TO "SYS"
/
GRANT "OEM_ADVISOR" TO "SYS"
/
GRANT "OEM_MONITOR" TO "DBSNMP"
/
GRANT "OEM_MONITOR" TO "SYS"
/
GRANT "GSMADMIN_ROLE" TO "GSMCATUSER"
/
GRANT "GSMADMIN_ROLE" TO "SYS"
/
GRANT "GSM_POOLADMIN_ROLE" TO "GSMCATUSER"
/
GRANT "GSM_POOLADMIN_ROLE" TO "SYS"
/
GRANT "GSM_POOLADMIN_ROLE" TO "GSMADMIN_INTERNAL"
/
GRANT "GGSYS_ROLE" TO "SYS"
/
GRANT "XDBADMIN" TO "DBA"
/
GRANT "XDBADMIN" TO "GSMADMIN_ROLE"
/
GRANT "XDBADMIN" TO "SYS"
/
GRANT "XDB_SET_INVOKER" TO "DBA"
/
GRANT "XDB_SET_INVOKER" TO "SYS"
/
GRANT "AUTHENTICATEDUSER" TO "SYS"
/
GRANT "XDB_WEBSERVICES" TO "SYS"
/
GRANT "XDB_WEBSERVICES_WITH_PUBLIC" TO "SYS"
/
GRANT "OLAP_XS_ADMIN" TO "DBA"
/
GRANT "OLAP_XS_ADMIN" TO "SYS"
/
GRANT "SODA_APP" TO "RESOURCE"
/
GRANT "SODA_APP" TO "SYS"
/
GRANT "SODA_APP" TO "XDB"
/
GRANT "DATAPATCH_ROLE" TO "SYS"
/
GRANT "WM_ADMIN_ROLE" TO "DBA"
/
GRANT "WM_ADMIN_ROLE" TO "WMSYS"
/
GRANT "JAVAUSERPRIV" TO "JAVASYSPRIV"
/
GRANT "JAVAUSERPRIV" TO "SYS"
/
GRANT "JAVAIDPRIV" TO "SYS"
/
GRANT "JAVASYSPRIV" TO "SYS"
/
GRANT "JAVADEBUGPRIV" TO "SYS"
/
GRANT "EJBCLIENT" TO "SYS"
/
GRANT "JMXSERVER" TO "SYS"
/
GRANT "DBJAVASCRIPT" TO "SYS"
/
GRANT "JAVA_ADMIN" TO "DBA"
/
GRANT "JAVA_ADMIN" TO "SYS"
/
GRANT "CTXAPP" TO "SYS"
/
GRANT "CTXAPP" TO "MDSYS"
/
GRANT "CTXAPP" TO "XDB"
/
GRANT "ORDADMIN" TO "SYS"
/
GRANT "DV_SECANALYST" TO "DV_ADMIN"
/
GRANT "DV_SECANALYST" TO "DV_OWNER"
/
GRANT "OLAP_DBA" TO "DBA"
/
GRANT "OLAP_DBA" TO "SYS"
/
GRANT "OLAP_USER" TO "SYS"
/
GRANT "RDFCTX_ADMIN" TO "SYS"
/
GRANT "LBAC_DBA" TO "SYS"
/
GRANT "LBAC_DBA" TO "LBACSYS"
/
GRANT "DV_MONITOR" TO "DV_OWNER"
/
GRANT "DV_MONITOR" TO "DBSNMP"
/
GRANT "DV_ADMIN" TO "DV_OWNER"
/
GRANT "DV_PATCH_ADMIN" TO "DV_OWNER"
/
GRANT "DV_STREAMS_ADMIN" TO "DV_OWNER"
/
GRANT "DV_GOLDENGATE_ADMIN" TO "DV_OWNER"
/
GRANT "DV_XSTREAM_ADMIN" TO "DV_OWNER"
/
GRANT "DV_GOLDENGATE_REDO_ACCESS" TO "DV_OWNER"
/
GRANT "DV_AUDIT_CLEANUP" TO "DV_OWNER"
/
GRANT "DV_DATAPUMP_NETWORK_LINK" TO "DV_OWNER"
/
GRANT "DV_POLICY_OWNER" TO "DV_OWNER"
/

