ALTER TABLE HOSPITALARIO.SNH_MST_HISTORIA_CLINICA MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_HISTORIA_CLINICA MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_DET_HISTORIA_CLINICA MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_DET_HISTORIA_CLINICA MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PARTO MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PARTO MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_POSTNATALES MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_POSTNATALES MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PSICOMOTOR MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PSICOMOTOR MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);
-----
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_ENFERMEDADES MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_ENFERMEDADES MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_EDUCACION MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_EDUCACION MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ENFER_FAMILIARES MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ENFER_FAMILIARES MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_EXAMEN_ADOLES MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_EXAMEN_ADOLES MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_EXAMEN_FISICO MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_EXAMEN_FISICO MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_FAMILIA MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_FAMILIA MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_HABITOS MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_HABITOS MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_HIST_SERVICIOS MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_HIST_SERVICIOS MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_MST_PSICOEMOCIONAL MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_PSICOEMOCIONAL MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_MST_VACUNAS MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_VACUNAS MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_MST_SEXUALIDAD MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_SEXUALIDAD MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_MST_VIDA_SOCIAL MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_VIDA_SOCIAL MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_REL_HIST_LABORAL MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_REL_HIST_LABORAL MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANT_UROLOGICO MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANT_UROLOGICO MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANT_PERSONALES MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANT_PERSONALES MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_MST_ANT_GINECOOBSTETRICO MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_MST_ANT_GINECOOBSTETRICO MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);

ALTER TABLE HOSPITALARIO.SNH_DET_FAMILIA MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_DET_FAMILIA MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);


ALTER TABLE HOSPITALARIO.SNH_DET_FAMILIA_CONVIVE MODIFY USUARIO_REGISTRO VARCHAR2 (50 BYTE);
ALTER TABLE HOSPITALARIO.SNH_DET_FAMILIA_CONVIVE MODIFY USUARIO_MODIFICACION VARCHAR2 (50 BYTE);
