ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP COLUMN PAREDES;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP COLUMN PISO;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP COLUMN TECHO;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP COLUMN AGUA;
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP COLUMN LUZ;