ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA RENAME COLUMN LACTANCIA_EXCLUSIVA TO TIPO_LACTANCIA;
ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA RENAME COLUMN DURACION_LACT_MIXTA TO DURACION_LACTANCIA;
ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA DROP COLUMN LACTANCIA_MIXTA;
ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA DROP COLUMN DURACION_LACT_EXCLUSIVA;

ALTER TABLE "HOSPITALARIO"."SNH_MST_ALIMEN_PEDIATRICA" ADD CONSTRAINT "FRK_SBC_CAT_CATALOGOS_LACTAN" FOREIGN KEY ("TIPO_LACTANCIA") REFERENCES "CATALOGOS"."SBC_CAT_CATALOGOS" ("CATALOGO_ID");