--- MODIFICAR TIPO DE DATOS 
--1
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO MODIFY HACIMIENTO NUMBER (10,0);

--2

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO MODIFY ESTADO_REGISTRO NUMBER (10,0);