---MODIFICACIONES EN FOREIGN KEYS
---1
ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_PSICOMOTOR DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_CONFDES;
--2

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_AGUA;

--3

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_LUZ;

--4

ALTER TABLE HOSPITALARIO.SNH_MST_ANTE_SOCIOECONOMICO DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_ANIM;

--5

ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_LACEXCL;

--6

ALTER TABLE HOSPITALARIO.SNH_MST_ALIMEN_PEDIATRICA DROP CONSTRAINT FRK_SBC_CAT_CATALOGOS_LACMIX;